import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/erro404">Erro404</Link>
        </li>
        <li>
          <Link to="/termospoliticas">Termospoliticas</Link>
        </li>
        <li>
          <Link to="/trabalheconosco">Trabalheconosco</Link>
        </li>
        <li>
          <Link to="/quemsomos">Quemsomos</Link>
        </li>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/faq">Faq</Link>
        </li>
        <li>
          <Link to="/desktoprepillinformaesemptystate">
            DesktopRePillInformaesEmptystate
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillinformaes">DesktopRePillInformaes</Link>
        </li>
        <li>
          <Link to="/desktoprepilljuntarentregasfour">
            DesktopRePillJuntarentregasFour
          </Link>
        </li>
        <li>
          <Link to="/desktoprepilljuntarentregasone">
            DesktopRePillJuntarentregasOne
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciar">DesktopRePillGerenciar</Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciarpularentrega">
            DesktopRePillGerenciarPularentrega
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciaratualizarreceita">
            DesktopRePillGerenciarAtualizarreceita
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciaralterarendereoone">
            DesktopRePillGerenciarAlterarendereoOne
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciaralterarformadepagamento">
            DesktopRePillGerenciarAlterarformadepagamento
          </Link>
        </li>
        <li>
          <Link to="/desktoprepillgerenciaralterarendereo">
            DesktopRePillGerenciarAlterarendereo
          </Link>
        </li>
        <li>
          <Link to="/desktoprepilljuntarentregasthree">
            DesktopRePillJuntarentregasThree
          </Link>
        </li>
        <li>
          <Link to="/desktoprepilljuntarentregas">
            DesktopRePillJuntarentregas
          </Link>
        </li>
        <li>
          <Link to="/desktoprepilljuntarentregastwo">
            DesktopRePillJuntarentregasTwo
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontameusdadoseditar">
            DesktopMinhacontaMeusdadoseditar
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontameusdadosalterarsenha">
            DesktopMinhacontaMeusdadosalterarsenha
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontahistricodepedidosone">
            DesktopMinhacontaHistricodepedidosOne
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontahistricodepedidos">
            DesktopMinhacontaHistricodepedidos
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontadetalhedopedidocarto">
            DesktopMinhacontaDetalhedopedidocarto
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontadetalhedopedidoboleto">
            DesktopMinhacontaDetalhedopedidoboleto
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontaendereosone">
            DesktopMinhacontaEndereosOne
          </Link>
        </li>
        <li>
          <Link to="/desktopminhacontaendereos">DesktopMinhacontaEndereos</Link>
        </li>
        <li>
          <Link to="/desktopminhacontacartes">DesktopMinhacontaCartes</Link>
        </li>
        <li>
          <Link to="/desktopminhacontacartesone">
            DesktopMinhacontaCartesOne
          </Link>
        </li>
        <li>
          <Link to="/desktopcarrinhoscompraavulsa">
            DesktopCarrinhoScompraavulsa
          </Link>
        </li>
        <li>
          <Link to="/desktopcarrinhorecorrenteavulsa">
            DesktopCarrinhoRecorrenteAvulsa
          </Link>
        </li>
        <li>
          <Link to="/desktopcarrinhoitemindisponvel">
            DesktopCarrinhoItemindisponvel
          </Link>
        </li>
        <li>
          <Link to="/desktopcarrinhocrosssellcepnoatendido">
            DesktopCarrinhoCrosssellCEPnoatendido
          </Link>
        </li>
        <li>
          <Link to="/desktopcarrinhocarrinhovazio">
            DesktopCarrinhoCarrinhovazio
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutreceitatwo">DesktopCheckoutReceitaTwo</Link>
        </li>
        <li>
          <Link to="/desktopcheckoutreceita">DesktopCheckoutReceita</Link>
        </li>
        <li>
          <Link to="/desktopcheckoutentregaformscompleto">
            DesktopCheckoutEntregaformscompleto
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutreceitaone">DesktopCheckoutReceitaOne</Link>
        </li>
        <li>
          <Link to="/desktopcheckoutentregaendereoadicionado">
            DesktopCheckoutEntregaendereoadicionado
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamento">DesktopCheckoutPagamento</Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentocarto">
            DesktopCheckoutPagamentocarto
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentopixtwo">
            DesktopCheckoutPagamentoPIXTwo
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutconclusocarto">
            DesktopCheckoutConclusocarto
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentopix">
            DesktopCheckoutPagamentoPIX
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentopixone">
            DesktopCheckoutPagamentoPIXOne
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutconclusocartoaccordionaberto">
            DesktopCheckoutConclusocartoAccordionaberto
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentorecusado">
            DesktopCheckoutPagamentorecusado
          </Link>
        </li>
        <li>
          <Link to="/desktopcheckoutpagamentocartosalvo">
            DesktopCheckoutPagamentocartosalvo
          </Link>
        </li>
        <li>
          <Link to="/produto">Produto</Link>
        </li>
        <li>
          <Link to="/categoriagrid">Categoriagrid</Link>
        </li>
        <li>
          <Link to="/categorialista">Categorialista</Link>
        </li>
        <li>
          <Link to="/busca">Busca</Link>
        </li>
        <li>
          <Link to="/semresultados">Semresultados</Link>
        </li>
        <li>
          <Link to="/logininserirdados">Logininserirdados</Link>
        </li>
        <li>
          <Link to="/logindadosinvalidos">Logindadosinvalidos</Link>
        </li>
        <li>
          <Link to="/loginrecuperacaodesenha">Loginrecuperacaodesenha</Link>
        </li>
        <li>
          <Link to="/loginsenhaalteradacomsucesso">
            Loginsenhaalteradacomsucesso
          </Link>
        </li>
        <li>
          <Link to="/cadastro">Cadastro</Link>
        </li>
        <li>
          <Link to="/cadastropessoafisica">Cadastropessoafisica</Link>
        </li>
        <li>
          <Link to="/cadastropessoajuridica">Cadastropessoajuridica</Link>
        </li>
        <li>
          <Link to="/template">Template</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
